spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:./target/test;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: create

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: warn
    net.ttddyy: debug