spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:./target/test;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      #ddl-auto: none
      ddl-auto: create
  main:
    banner-mode: off

logging:
  level:
    root: warn
    net.ttddyy: debug
    com.sloboda: info

decorator:
  datasource:
    datasource-proxy:
      count-query: true