spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:./target/test;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: info
    net.ttddyy: debug